### ISSUE TITLE
ANNIS Corpling redirects for minted URLs

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/misc-development#8]
We have a number of URLs in publications that were minted when ANNIS was on the corpling server with a corpling URL. We need to figure out how to set up a redirect. Is there any way to recover those minted URLs from the old ANNIS instance?

**Comment by ctschroeder** [comment]
minted link challenge: minted links go to ANNIS not to the scriptorium instance (note that the minted links do not have the scriptorium subdirectory)

To redirect minted links: minted links of Coptic stuff would have to go to scriptorium and non-Coptic go to another server but it's not clear from the URLs which are scriptorium links. 

Anyone who clicks on an old link will go to the scriptorium 4.3 release on the GUcorpling server, not to the updated scriptorium instance on the Scriptorium server

**Comment by ctschroeder** [comment]
(FYI for future links the minted links we make from now on on the new server will work as long as we have access to the database and we own the domain/keep the domain and subdomain stable.)

**Comment by ctschroeder** [comment]
@amir-zeldes can we close this?

**Comment by amir-zeldes** [comment]
I think so!
